### ISSUE TITLE
inserting node with high wrong count back into queue

### ISSUE THREAD

**Issue by DrGorochinn** [FeenoPH/ITS2-QuizGame#3]
Make the insertion of a node with a high # of timesWrong into the queue a bit more random, as it stands, it just asks the most wrong quesion every second time.

**Comment by FeenoPH** [comment]
I didn't want to make it more random, because that has the potential of messing up the rest of the queue, so instead, I limited the maximum number of times you have to continue answering the same question to 4, so that we still prioritize the questions that the user commonly gets wrong, without making it too frustrating for the user in the event that they continue to get the same question wrong. We are still able to alter the amount that these questions are limited to, so if we want to set the limit higher or lower, we are able to.
